# Generated by Django 6.0.6 on 2026-09-09 14:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(help_text='Masalan: Humo - asosiy', max_length=80, verbose_name='Karta nomi')),
                ('raqam', models.CharField(max_length=30, verbose_name='Karta raqami')),
                ('egasi', models.CharField(blank=True, max_length=80, verbose_name='Karta egasi')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Karta',
                'verbose_name_plural': 'Kartalar',
                'ordering': ['-faol', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='Tranzaksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('hisob', "Hisoblangan kurs to'lovi"), ('tolov', "To'lov qabul qilindi"), ('chegirma', 'Chegirma'), ('qaytarish', 'Pul qaytarildi'), ('qarz', "O'qituvchi qarzi (oldindan to'lovga o'tdi)")], max_length=20, verbose_name='Turi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Summa (so'm)")),
                ('sana', models.DateField(default=datetime.date.today, verbose_name='Sana')),
                ('usul', models.CharField(blank=True, choices=[('naqd', 'Naqd pul'), ('plastik', 'Plastik karta')], max_length=10, verbose_name="To'lov usuli")),
                ('karta_raqami', models.CharField(blank=True, max_length=30, verbose_name='Karta raqami')),
                ('davr', models.DateField(blank=True, help_text="Faqat hisoblangan kurs to'lovlari uchun.", null=True, verbose_name='Hisob davri (oy boshi)')),
                ('kunlar', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hisoblangan kunlar')),
                ('izoh', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('karta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tranzaksiyalar', to='payments.karta', verbose_name='Karta')),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranzaksiyalar', to='students.oquvchi', verbose_name="O'quvchi")),
                ('yaratgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-sana', '-id'],
                'indexes': [models.Index(fields=['tur', 'sana'], name='payments_tr_tur_936541_idx'), models.Index(fields=['oquvchi', 'sana'], name='payments_tr_oquvchi_026000_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tur', 'hisob')), fields=('oquvchi', 'davr'), name='bir_oyga_bitta_hisob')],
            },
        ),
    ]
