# Generated by Django 6.0.6 on 2026-09-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tranzaksiya',
            name='karta',
        ),
        migrations.RemoveField(
            model_name='tranzaksiya',
            name='karta_raqami',
        ),
        migrations.DeleteModel(
            name='Karta',
        ),
    ]
