# Generated by Django 6.1.1 on 2026-09-15 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0009_arxiv_chetlatildi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsXabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qabul_qiluvchi', models.CharField(choices=[('ota', 'Ota'), ('ona', 'Ona')], max_length=10, verbose_name='Kimga')),
                ('telefon', models.CharField(max_length=30, verbose_name='Telefon')),
                ('matn', models.TextField(verbose_name='Xabar matni')),
                ('davr', models.DateField(verbose_name='Qaysi oy uchun (oy boshi)')),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="O'sha paytdagi qarz")),
                ('holat', models.CharField(choices=[('navbatda', 'Navbatda'), ('olindi', 'Ilova oldi'), ('jonatildi', "Jo'natildi"), ('xato', 'Xato'), ('bekor', 'Bekor qilindi')], default='navbatda', max_length=15, verbose_name='Holati')),
                ('urinishlar', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar')),
                ('xato_matni', models.CharField(blank=True, max_length=255, verbose_name='Xato izohi')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, verbose_name="Navbatga qo'yilgan")),
                ('olingan', models.DateTimeField(blank=True, null=True, verbose_name='Ilova olgan vaqt')),
                ('jonatilgan', models.DateTimeField(blank=True, null=True, verbose_name="Jo'natilgan vaqt")),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_xabarlar', to='students.oquvchi', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'SMS xabar',
                'verbose_name_plural': 'SMS xabarlar',
                'ordering': ['-davr', '-id'],
                'indexes': [models.Index(fields=['holat'], name='sms_smsxaba_holat_f35564_idx'), models.Index(fields=['davr'], name='sms_smsxaba_davr_810611_idx')],
                'constraints': [models.UniqueConstraint(fields=('oquvchi', 'davr', 'qabul_qiluvchi'), name='oyiga_bitta_sms')],
            },
        ),
    ]
