# Generated by Django 6.1.1 on 2026-09-15 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
        ('students', '0009_arxiv_chetlatildi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qurilma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qurilma_id', models.CharField(help_text="Ilova o'rnatilganda bir marta yaratiladigan barqaror belgi.", max_length=64, unique=True, verbose_name='Qurilma belgisi')),
                ('nomi', models.CharField(max_length=100, verbose_name='Nomi')),
                ('ishlab_chiqaruvchi', models.CharField(blank=True, max_length=60, verbose_name='Ishlab chiqaruvchi')),
                ('model', models.CharField(blank=True, max_length=60, verbose_name='Modeli')),
                ('android', models.CharField(blank=True, max_length=20, verbose_name='Android')),
                ('ilova_versiya', models.CharField(blank=True, max_length=20, verbose_name='Ilova versiyasi')),
                ('kalit', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Maxfiy kalit')),
                ('faol', models.BooleanField(default=True, help_text="O'chirilsa, qurilma saytga ulana olmaydi va SMS ololmaydi.", verbose_name='Faol')),
                ('batareya', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Batareya (%)')),
                ('qoshilgan', models.DateTimeField(auto_now_add=True, verbose_name='Ulangan vaqt')),
                ('oxirgi_aloqa', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi aloqa')),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'ordering': ['-oxirgi_aloqa', 'nomi'],
            },
        ),
        migrations.CreateModel(
            name='UlanishKodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=12, unique=True, verbose_name='Kod')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('amal_qiladi', models.DateTimeField(verbose_name='Amal qilish muddati')),
                ('ishlatilgan', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan')),
            ],
            options={
                'verbose_name': 'Ulanish kodi',
                'verbose_name_plural': 'Ulanish kodlari',
                'ordering': ['-yaratilgan'],
            },
        ),
        migrations.AddField(
            model_name='smsxabar',
            name='berilgan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qurilmaga berilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='smsxabar',
            name='holat',
            field=models.CharField(choices=[('navbatda', 'Navbatda (yuborilmagan)'), ('berildi', 'Qurilmaga berildi'), ('olindi', 'Ilova oldi'), ('jonatildi', "Jo'natildi"), ('xato', 'Xato'), ('bekor', 'Bekor qilindi')], default='navbatda', max_length=15, verbose_name='Holati'),
        ),
        migrations.CreateModel(
            name='Bildirishnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('ulandi', 'Qurilma ulandi'), ('uzildi', 'Qurilma uzildi'), ('yuborildi', 'Xabarlar yuborildi'), ('xato', 'Xatolik'), ('malumot', "Ma'lumot")], default='malumot', max_length=20, verbose_name='Turi')),
                ('matn', models.CharField(max_length=255, verbose_name='Matn')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('korildi', models.BooleanField(default=False, verbose_name="Ko'rildi")),
                ('qurilma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bildirishnomalar', to='sms.qurilma', verbose_name='Qurilma')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-yaratilgan', '-id'],
            },
        ),
        migrations.AddField(
            model_name='smsxabar',
            name='qurilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xabarlar', to='sms.qurilma', verbose_name='Qaysi qurilmadan'),
        ),
        migrations.CreateModel(
            name='SimKarta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_id', models.IntegerField(verbose_name='SIM belgisi (subscriptionId)')),
                ('nomi', models.CharField(max_length=60, verbose_name='Nomi')),
                ('raqam', models.CharField(blank=True, max_length=30, verbose_name='Raqami')),
                ('slot', models.PositiveSmallIntegerField(default=0, verbose_name='Uyasi')),
                ('faol', models.BooleanField(default=True, verbose_name='Ishlatilsin')),
                ('qurilma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simlar', to='sms.qurilma', verbose_name='Qurilma')),
            ],
            options={
                'verbose_name': 'SIM karta',
                'verbose_name_plural': 'SIM kartalar',
                'ordering': ['qurilma', 'slot'],
            },
        ),
        migrations.AddField(
            model_name='smsxabar',
            name='sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xabarlar', to='sms.simkarta', verbose_name='Qaysi SIM dan'),
        ),
        migrations.AddIndex(
            model_name='smsxabar',
            index=models.Index(fields=['qurilma', 'holat'], name='sms_smsxaba_qurilma_038b69_idx'),
        ),
        migrations.AddField(
            model_name='ulanishkodi',
            name='qurilma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kodlar', to='sms.qurilma', verbose_name='Ulangan qurilma'),
        ),
        migrations.AddField(
            model_name='ulanishkodi',
            name='yaratgan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi'),
        ),
        migrations.AddIndex(
            model_name='bildirishnoma',
            index=models.Index(fields=['korildi'], name='sms_bildiri_korildi_5b890b_idx'),
        ),
        migrations.AddConstraint(
            model_name='simkarta',
            constraint=models.UniqueConstraint(fields=('qurilma', 'sim_id'), name='qurilmada_bitta_sim'),
        ),
    ]
