# Generated by Django 6.1.1 on 2026-09-16 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_qurilma_ulanishkodi_smsxabar_berilgan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulOynasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ochilgan', models.DateTimeField(auto_now_add=True, verbose_name='Ochilgan vaqt')),
                ('ochgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qabul_oynalari', to=settings.AUTH_USER_MODEL, verbose_name='Kim ochdi')),
            ],
            options={
                'verbose_name': 'Qabul oynasi',
                'verbose_name_plural': 'Qabul oynalari',
                'ordering': ['-ochilgan'],
            },
        ),
    ]
