# Generated by Django 6.0.6 on 2026-09-09 14:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Guruh nomi')),
                ('oylik_toluv', models.DecimalField(decimal_places=2, default=0, help_text="Yangi o'quvchi qo'shilganda shu summa avtomatik qo'yiladi.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Oylik kurs to'lovi (so'm)")),
                ('jadval', models.CharField(blank=True, help_text='Masalan: Du/Chor/Jum 15:00', max_length=200, verbose_name='Dars jadvali')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Oquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=60, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=60, verbose_name='Familiya')),
                ('telefon', models.CharField(blank=True, max_length=30, verbose_name="O'quvchi telefoni")),
                ('ota_telefon', models.CharField(blank=True, max_length=30, verbose_name='Ota telefoni')),
                ('ona_telefon', models.CharField(blank=True, max_length=30, verbose_name='Ona telefoni')),
                ('oylik_toluv', models.DecimalField(decimal_places=2, default=0, help_text="Bir oylik to'liq narx. Kunlik narx = shu summa / oydagi kunlar soni.", max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Oylik kurs to'lovi (so'm)")),
                ('boshlangan_sana', models.DateField(default=datetime.date.today, help_text='Birinchi oy shu sanadan keyingi oyning 1-sanasigacha kunlab hisoblanadi.', verbose_name='Kursga kelgan sana')),
                ('faol', models.BooleanField(default=True, verbose_name="Ro'yxatda (kursga keladi)")),
                ('chiqarilgan_sana', models.DateField(blank=True, null=True, verbose_name='Kursdan chiqarilgan sana')),
                ('chiqarish_sababi', models.CharField(blank=True, max_length=200, verbose_name='Chiqarish sababi')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oquvchilar', to='students.guruh', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['familiya', 'ism'],
                'indexes': [models.Index(fields=['faol'], name='students_oq_faol_2adf16_idx'), models.Index(fields=['familiya', 'ism'], name='students_oq_familiy_705129_idx')],
            },
        ),
    ]
