# Generated by Django 6.0.6 on 2026-09-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guruh',
            name='jadval',
        ),
    ]
