# Generated by Django 6.0.6 on 2026-09-10 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_guruh_jadval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guruh',
            name='oylik_toluv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Oylik kurs to'lovi (so'm)"),
        ),
    ]
