# Generated by Django 6.0.6 on 2026-09-10 03:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_guruh_oylik_toluv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oquvchi',
            name='oylik_toluv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Bo'sh qoldirilsa, guruh narxi olinadi.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Oylik kurs to'lovi (so'm)"),
        ),
    ]
