# Generated by Django 6.0.6 on 2026-09-10 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_oquvchi_oylik_toluv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oquvchi',
            name='boshlangan_sana',
            field=models.DateField(default=datetime.date.today, help_text='Shu oyda qatnashgan kunlari keyingi oyning 1-sanasida hisoblanadi.', verbose_name='Kursga kelgan sana'),
        ),
    ]
