# Generated by Django 6.0.6 on 2026-09-10 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_xodim_karta_raqami_and_more'),
        ('students', '0005_alter_oquvchi_boshlangan_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='oqituvchi',
            field=models.ForeignKey(blank=True, help_text="Guruhga biriktirilgan o'qituvchi shu guruh o'quvchilarini ko'radi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guruhlar', to='staff.xodim', verbose_name="O'qituvchi"),
        ),
    ]
