# Generated by Django 6.1.1 on 2026-09-12 09:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_guruh_oqituvchi_hisobga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabab', models.CharField(choices=[('oqish', "O'qishga kirdi"), ('sertifikat', 'Sertifikat oldi'), ('haydaldi', 'Guruhdan haydaldi')], max_length=20, verbose_name='Sababi')),
                ('guruh_nomi', models.CharField(blank=True, help_text="Guruh keyin o'chirilsa ham nomi shu yerda saqlanib qoladi.", max_length=100, verbose_name='Guruh nomi')),
                ('biologiya_bali', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Biologiya bali')),
                ('jami_ball', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jami ball')),
                ('sertifikat', models.CharField(blank=True, max_length=200, verbose_name='Sertifikat')),
                ('sana', models.DateField(default=datetime.date.today, verbose_name='Arxivlangan sana')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('guruh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arxivlanganlar', to='students.guruh', verbose_name='Arxivlashdagi guruhi')),
                ('oquvchi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arxiv', to='students.oquvchi', verbose_name="O'quvchi")),
                ('yaratgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arxivlagani', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
            ],
            options={
                'verbose_name': 'Arxiv yozuvi',
                'verbose_name_plural': 'Arxiv',
                'ordering': ['-sana', '-id'],
                'indexes': [models.Index(fields=['sabab'], name='students_ar_sabab_9add16_idx')],
            },
        ),
    ]
