# Generated by Django 6.1.1 on 2026-09-12 12:24

from django.db import migrations, models


def haydaldi_chetlatildi(apps, schema_editor):
    """Eski yozuvlar yangi kodga o'tkaziladi."""
    apps.get_model('students', 'Arxiv').objects.filter(
        sabab='haydaldi').update(sabab='chetlatildi')


def chetlatildi_haydaldi(apps, schema_editor):
    apps.get_model('students', 'Arxiv').objects.filter(
        sabab='chetlatildi').update(sabab='haydaldi')


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_arxiv'),
    ]

    operations = [
        migrations.RunPython(haydaldi_chetlatildi, chetlatildi_haydaldi),
        migrations.AlterField(
            model_name='arxiv',
            name='sabab',
            field=models.CharField(choices=[('oqish', "O'qishga kirdi"), ('sertifikat', 'Sertifikat oldi'), ('chetlatildi', 'Guruhdan chetlatildi')], max_length=20, verbose_name='Sababi'),
        ),
    ]
