# Generated by Django 6.0.6 on 2026-09-09 14:36

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=60, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=60, verbose_name='Familiya')),
                ('lavozim', models.CharField(blank=True, help_text="Masalan: o'qituvchi, administrator, farrosh", max_length=80, verbose_name='Lavozim')),
                ('telefon', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('karta_raqami', models.CharField(blank=True, help_text="Oylik plastikka o'tkazilganda ishlatiladi.", max_length=30, verbose_name='Plastik karta raqami')),
                ('oylik_maosh', models.DecimalField(decimal_places=2, default=0, help_text='Har oyning 1-sanasida shu summa avtomatik hisoblanadi.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Oylik maosh (so'm)")),
                ('ishga_kirgan_sana', models.DateField(default=datetime.date.today, verbose_name='Ishga kirgan sana')),
                ('faol', models.BooleanField(default=True, verbose_name='Ishlayapti')),
                ('ishdan_ketgan_sana', models.DateField(blank=True, null=True, verbose_name='Ishdan ketgan sana')),
                ('izoh', models.TextField(blank=True, verbose_name='Izoh')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['familiya', 'ism'],
            },
        ),
        migrations.CreateModel(
            name='XodimTranzaksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('hisob', 'Hisoblangan oylik'), ('avans', 'Avans berildi'), ('oylik', 'Oylik berildi'), ('bonus', 'Bonus / ustama'), ('jarima', 'Ushlab qolindi')], max_length=20, verbose_name='Turi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Summa (so'm)")),
                ('sana', models.DateField(default=datetime.date.today, verbose_name='Sana')),
                ('usul', models.CharField(blank=True, choices=[('naqd', 'Naqd pul'), ('plastik', 'Plastik karta')], max_length=10, verbose_name="To'lov usuli")),
                ('karta_raqami', models.CharField(blank=True, max_length=30, verbose_name='Karta raqami')),
                ('davr', models.DateField(blank=True, null=True, verbose_name='Hisob davri (oy boshi)')),
                ('kunlar', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Hisoblangan kunlar')),
                ('izoh', models.CharField(blank=True, max_length=255, verbose_name='Izoh')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranzaksiyalar', to='staff.xodim', verbose_name='Xodim')),
                ('yaratgan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
            ],
            options={
                'verbose_name': 'Xodim tranzaksiyasi',
                'verbose_name_plural': 'Xodim tranzaksiyalari',
                'ordering': ['-sana', '-id'],
                'indexes': [models.Index(fields=['tur', 'sana'], name='staff_xodim_tur_dc0322_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('tur', 'hisob')), fields=('xodim', 'davr'), name='xodimga_bir_oyga_bitta_hisob')],
            },
        ),
    ]
