# Generated by Django 6.0.6 on 2026-09-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_xodim_foydalanuvchi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodim',
            name='lavozim',
        ),
    ]
