# Generated by Django 6.0.6 on 2026-09-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_xodim_lavozim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xodim',
            name='karta_raqami',
        ),
        migrations.RemoveField(
            model_name='xodimtranzaksiya',
            name='karta_raqami',
        ),
    ]
