# Generated by Django 6.0.6 on 2026-09-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foydalanuvchi',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('oqituvchi', "O'qituvchi")], default='oqituvchi', max_length=20, verbose_name='Rol'),
        ),
    ]
